### ISSUE TITLE
unity Moralis problem

### ISSUE THREAD

**Issue by JohnConstine** [ethereum-boilerplate/ethereum-unity-boilerplate#12]
I have a problem from unity Moralis template. Why is the contract method not called through the contract address? Why?  I  cant use it, Please sir, I have not idea.

**Comment by xactant** [comment]
@JohnConstine,

Hello, Is this through the Web3API? Please provide an example of the method you are calling with parameters. I will see what is going on.  

Thank you! 

David

**Comment by JohnConstine** [comment]
Hello, sir, I have solved it through a good method to directly generate contract data. I'll send you an email later, sir.

**Comment by JohnConstine** [comment]
Another question, sir, I don't know. How can I set “SPeedy Nodes” in the unity template? Can you teach me?

**Comment by JohnConstine** [comment]
const NODE_URL = "YOUR SPEEDY NODE URL HERE";
const provider = new Web3.providers.HttpProvider(NODE_URL);
const web3 = new Web3(provider);

this is JS Code ，have C# ?

**Comment by xactant** [comment]
Nethereum integration is checked into the features/walletconnect_integration branch. Please be advised that this branch is development code and therefore not stable.
