### ISSUE TITLE
Speedy Nodes

### ISSUE THREAD

**Issue by JohnConstine** [ethereum-boilerplate/ethereum-unity-boilerplate#16]
Another question, sir, I don't know. How can I set “SPeedy Nodes” in the unity template? Can you teach me?

**Comment by JohnConstine** [comment]
Sir？

**Comment by xactant** [comment]
I am working on this issue ...

**Comment by xactant** [comment]
UPDATE I have checked code for this into the features/walletconnect_integration branch. This branch is still in development. In a few days I will include wrapper objects so that this functionality can be used under the Moralis namespace.

**Comment by JohnConstine** [comment]
OK thank you  sir

**Comment by xactant** [comment]
Nethereum integration is checked into the features/walletconnect_integration branch. Please be advised that this branch is development code and therefore not stable.
