### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by JohnConstine** [ethereum-boilerplate/ethereum-unity-boilerplate#20]
public Object CallApi(String path, RestSharp.Method method, Dictionary<String, String> queryParams, String postBody,
            Dictionary<String, String> headerParams, Dictionary<String, String> formParams, 
            Dictionary<String, FileParameter> fileParams, String[] authSettings)

Like this... ，Why use synchronous call Web3 API，When I have a lot of NFT assets, they will jam the whole unity page. block

**Comment by ivan-liljeqvist** [comment]
Post questions in the forum https://forum.moralis.io/t/ethereum-unity3d-boilerplate-questions/4553/21 thanks
