### ISSUE TITLE
Unity Issues

### ISSUE THREAD

**Issue by nasiralis** [ethereum-boilerplate/ethereum-unity-boilerplate#21]
Below errors propped up, using Unity 2020,03.26f1, kindly help.

![image](https://user-images.githubusercontent.com/35076328/150489076-01261121-97ed-49dd-92b4-f27de95ec4b2.png)

**Comment by ivan-liljeqvist** [comment]
Post questions here thanks https://forum.moralis.io/t/ethereum-unity3d-boilerplate-questions/4553/21
