### ISSUE TITLE
Project is missing meta files

### ISSUE THREAD

**Issue by bmateus** [ethereum-boilerplate/ethereum-unity-boilerplate#3]
Need to commit meta files otherwise things will be broken (references, settings)

Current .gitignore is ignoring all meta file
Recommend using the .gitignore for unity at: 

https://github.com/github/gitignore/blob/master/Unity.gitignore

**Comment by xactant** [comment]
Good catch. Thank you.

**Comment by xactant** [comment]
Fix checked into branch bugs/bugs_20211213
