### ISSUE TITLE
Replace Wallet Connect with In-Browser wallet Interface for WebGL Projects

### ISSUE THREAD

**Issue by xactant** [ethereum-boilerplate/ethereum-unity-boilerplate#32]
For WebGL Wallet Connect displays a QR code similar to Desktop builds.

Update the Moralis / Unity3d SDK to include a WASM bridge to Metamask (or other wallets) in browser for WebGL so that these provide the a similar user experience as a regular JS Web3 application.

**Comment by lfgdevops** [comment]
very interested in this

**Comment by joksa** [comment]
Please update when it is done. Entire project depends on this feature. Thanks

**Comment by caiocabralbr** [comment]
Any update?

**Comment by xactant** [comment]
Working branch is at: https://github.com/metaversesdk/web3unity/tree/features/webgl-metamask

Integration is complete here but a lot of clean up is needed still. Additionally the methods for interacting with the wallets using wallet connect and the webgl/metamask integration are very dissimilar at the moment. Working to clean that up.

**Comment by RgonzalezSLC** [comment]
> Working branch is at: https://github.com/metaversesdk/web3unity/tree/features/webgl-metamask
> 
> Integration is complete here but a lot of clean up is needed still. Additionally the methods for interacting with the wallets using wallet connect and the webgl/metamask integration are very dissimilar at the moment. Working to clean that up.

Could this feature be used for a project in production?

**Comment by xactant** [comment]
Included in PR#73
