### ISSUE TITLE
WebSocket Conflicts

### ISSUE THREAD

**Issue by WoodsFiend** [ethereum-boilerplate/ethereum-unity-boilerplate#45]
In the MoralisClientWebSocket script, there are references to WebSocket. This can collide with other classes named the same. In my case I also use Photon which has its own implementation of WebSocket. To resolve I just directly defined the namespace in the script.

```
    public class MoralisClientWebSocket : IClientWebSocket
    {
        private Moralis.Network.Client.WebSocket webSocket = null;
        public object Mutex = '\0';
        public Queue<byte[]> MessageQueue;

        public MoralisClientWebSocket(string uri, Dictionary<string, string> headers = null)
        {
            webSocket = new Moralis.Network.Client.WebSocket(uri, headers);
            MessageQueue = new Queue<byte[]>();
            webSocket.OnMessage += OnReceiveMessage;
        }
```

This also occurs in the WalletConnectSharp NativeWebSocketTransport script. The solution was the same.
```
    public class NativeWebSocketTransport : MonoBehaviour, ITransport
    {
        private bool opened = false;
        private bool closed = false;

        private NativeWebSocket.WebSocket nextClient;
        private NativeWebSocket.WebSocket client;
```

**Comment by WoodsFiend** [comment]
Ya it seems they didn't namespace the photon WebSocket now that I look at it. Thanks for pointing that out :)

**Comment by xactant** [comment]
Thank you for confirming. As this is not an issue with the Moralis / Unity SDK I will close out this issue.

**Comment by caiocabralbr** [comment]
I solved it with this:

https://forum.moralis.io/t/ethereum-unity3d-boilerplate-questions/4553/284?u=caiocabralbr

in `Assets\MoralisWeb3ApiSdk\WalletConnectSharp.Unity\Network\Client\WebSockets.jslib`
just change the name to: WebSockets2.jslib

will be like `Assets\MoralisWeb3ApiSdk\WalletConnectSharp.Unity\Network\Client\WebSockets2.jslib`

in WebSockets2.jslib, find and change this snippet code:
`		 * Instance structure:
		 * {
		 * 	url: string,
		 * 	ws: WebSocket
		 * }`
		 
and change to:

`		 * Instance structure:
		 * {
		 * 	url: string,
		 * 	ws: WebSocket2
		 * }`
