### ISSUE TITLE
ACL is always set to "Master Key Only"

### ISSUE THREAD

**Issue by Rpacho** [ethereum-boilerplate/ethereum-unity-boilerplate#46]
Every time I created a Class, the ACL was always set to "Master Key Only". Even after making sure that my ACL is set to PublicReadAccess and PublicWriteAccess to true, it was always set to "Master Key Only". 

`        
MoralisAcl acl = new MoralisAcl()`
`{ `
        `PublicReadAccess = true, `
       `PublicWriteAccess = true `
`};`
`room.ACL = acl;`
`try`
` {`
      `await room.SaveAsync(); `
`}`
`catch(Exception e)`
`{`
     `Debug.Log("Cannot Save Room to database " + e);`
`}
`

![image](https://user-images.githubusercontent.com/46900743/153693450-c5db4f8b-1b0d-44e8-929e-c0903217c9c6.png)

**Comment by ivan-liljeqvist** [comment]
Hi there please post in https://forum.moralis.io and devs will check your code
