### ISSUE TITLE
WEBGL: Websocket.instance.ws.onopen

### ISSUE THREAD

**Issue by RgonzalezSLC** [ethereum-boilerplate/ethereum-unity-boilerplate#48]
I’m testing the demo scene and when I run the game in my browser, I get this error:

> An error ocurred running the unity context on this page. See your browser JavaScript console for mora info.
> The error whas: ReferenceError: Runtime is not defined at WebSocket.instance.ws.onopen(https://********/build/Build.framework.js.br:3:58138)

![capture-2122022](https://user-images.githubusercontent.com/89937681/153724523-8da6426c-e1d1-40cb-88ef-d29d15be6ce8.png)

**Comment by RgonzalezSLC** [comment]
I have not made any changes to the code, I just put the parameters of my moralis server and compiled the game

**Comment by xactant** [comment]
I did a fresh pull and build for WebGL and Authentication was successful and the demo worked as expected.

From the error you posted it look like something with the Wallet Connect build or connection failed.

Should look something like this:

```
Connecting to Moralis ...
t5.framework.js.gz:2 Connected to Moralis!
t5.framework.js.gz:2 [WebSocket] Subs Cleared
t5.framework.js.gz:2 Waiting for Wallet connection
t5.framework.js.gz:2 wc:21e80625-56e9-4210-8aeb-627f2d563919@1?bridge=https%3A%2F%2Fq.bridge.walletconnect.org&key=e957407c78ea9d814f361fd85b9ee54f84b857f79b33143a88f758ce45b8349a
t5.framework.js.gz:2 [WebSocket] Subs Cleared
t5.framework.js.gz:2 [WebSocket] Waiting for Open wss://q.bridge.walletconnect.org
t5.framework.js.gz:2 Closing Websocket
t5.framework.js.gz:2 [WebSocket] Queued 0 subscriptions
t5.framework.js.gz:2 [WebSocket] Flushing Queue
t5.framework.js.gz:2 [WebSocket] Queue Count: 0
t5.framework.js.gz:2 [WebSocket] Queue Flushed
t5.framework.js.gz:2 [WebSocket] Opened wss://q.bridge.walletconnect.org
t5.framework.js.gz:2 [WebSocket] Open Completed
t5.framework.js.gz:2 [WebSocket] Subscribe to 7ddc8920-9a61-4034-8a3e-e6a8931eedaf
```

Please double check that you followed all of the setup steps in the README and that your Moralis Server URI, Application ID and Web 3 Rpc Node Uri are correct.

Please clear the project in the build folder and re-try the Build and Run

If the problem persists please include your platform, build platform, and Unity version.

**Comment by RgonzalezSLC** [comment]
I have already deleted the build folder and built the project again but the same error persists.
Unity version: 2021.2.4f1
Build platform: WebG
![Captura de pantalla 2022-02-12 222239](https://user-images.githubusercontent.com/89937681/153735634-64990443-727a-44e3-be8b-7ab1009a2cd4.png)
![Captura de pantalla 2022-02-12 222310](https://user-images.githubusercontent.com/89937681/153735637-d04b8a5f-acce-4769-8993-c706d2f8a6af.png)
![Captura de pantalla 2022-02-12 222448](https://user-images.githubusercontent.com/89937681/153735638-37028c4d-7dc1-422e-b981-bb5852e4ee74.png)
L

**Comment by RgonzalezSLC** [comment]
>

**Comment by xactant** [comment]
Okay I will download the 2021.2.4f1 and try the build with that version.

**Comment by imtrobin** [comment]
I have same issue. When I build , and I scan the QR code, it (metamask) succeed on my phone but the qr code doesn't disappear

**Comment by jepsilon** [comment]
Hello Moralis Dev team, I think the problem is because Unity WebGL webSocket.jslib, I have changed and Socket has opened successfully, it is requesting in the wallet the conection but it is not requesting sign after that ...

**Comment by jepsilon** [comment]
Here the Referenced solution for jslib and Unity >= 2021.2

**Comment by xactant** [comment]
reviewing PR with Koen for this. Should be merging soon.
