### ISSUE TITLE
BUG: Cannot set ACL to Public

### ISSUE THREAD

**Issue by Rpacho** [ethereum-boilerplate/ethereum-unity-boilerplate#49]
Every time I create a Class and set the ACL to Public, It always defaults to "Master Key Only". As a result, I cannot query the Class data.

![image](https://user-images.githubusercontent.com/46900743/153820607-f493202f-dc35-43a3-8cf5-27ade9a82553.png)

**Comment by xactant** [comment]
Looking ...

**Comment by xactant** [comment]
Looks like serialization of the ACL is off so even though it is passed back, it is not being saved. Will create a patch today.

**Comment by xactant** [comment]
Updated with pull-request #53
