### ISSUE TITLE
The format of the URI could not be determined.

### ISSUE THREAD

**Issue by Oberhaim** [ethereum-boilerplate/ethereum-unity-boilerplate#51]
On the demo scene , I am Having this issue when connecting with wallet connect with trust wallet:

UriFormatException: Invalid URI: The format of the URI could not be determined. System.Uri.CreateThis (System.String uri, System.Boolean dontEscape

This shows on the consol after I authentify with the app. But the QR still apears !

**Comment by xactant** [comment]
Make sure that the Server URI and RPC Node URI values are set in the MoralisSetup object in the demo scene.

**Comment by Oberhaim** [comment]
Yes, I made sure of that a hundred times. But it didn't change anything! :( 
I had to create my own scene to test moralis but i struggle with issue #52 

using unity 2020.3.23f1

**Comment by xactant** [comment]
Closing issue - was able to help the customer in the forum.
