### ISSUE TITLE
UserServiceExtensions : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Oberhaim** [ethereum-boilerplate/ethereum-unity-boilerplate#52]
Hi there, thanks for the amazing work! 
I am having an issue when I try to authenticate with the QR code: 
When I use Trust Wallet or Iam Token to capture the QR, it sends the request correctly, then receive back the confimation message inside the wallet. 
However when accepting the request, the loggin fails, and this shows in Unity's consol, related to UserServiceExtensions.cs : 

NullReferenceException: Object reference not set to an instance of an object
Moralis.Platform.Services.ClientServices.UserServiceExtensions+<>c__DisplayClass18_0`1[TUser].<LogInWithAsync>b__0 (System.Threading.Tasks.Task`1[TResult] task) (at Assets/MoralisWeb3ApiSdk/Moralis/MoralisDotNet/Platform/Services/ClientServices/UserServiceExtensions.cs:191)
Moralis.Platform.Utilities.InternalExtensions+<>c__DisplayClass5_0`2[TIn,TResult].<OnSuccess>b__0 (System.Threading.Tasks.Task t) (at Assets/MoralisWeb3ApiSdk/Moralis/MoralisDotNet/Platform/Utilities/InternalExtensions.cs:45)
Moralis.Platform.Utilities.InternalExtensions+<>c__DisplayClass7_0`1[TResult].<OnSuccess>b__0 (System.Threading.Tasks.Task t) (at Assets/MoralisWeb3ApiSdk/Moralis/MoralisDotNet/Platform/Utilities/InternalExtensions.cs:72)
System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Threading.Tasks.Task.Execute () (at <695d1cc93cca45069c528c15c9fdd749>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Moralis.Platform.Utilities.InternalExtensions+<>c__DisplayClass7_0`1[TResult].<OnSuccess>b__0 (System.Threading.Tasks.Task t) (at Assets/MoralisWeb3ApiSdk/Moralis/MoralisDotNet/Platform/Utilities/InternalExtensions.cs:59)
System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Threading.Tasks.Task.Execute () (at <695d1cc93cca45069c528c15c9fdd749>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
MainMenuScript+<WalletConnectHandler>d__11.MoveNext () (at Assets/MoralisWeb3ApiSdk/Example/Scripts/MainMenuScript.cs:199)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

What am I missing ? 

thanks !

**Comment by xactant** [comment]
This is related to a defect that was patched on Friday - please either:
1) Copy the _WalletConnectHandler_ method in the _MainMenuScript.cs_ from the github repo to your project or
2) Update your project to v1.0.5

**Comment by Oberhaim** [comment]
Hi thanks for the quick reply ! 
I'm already on v1.0.5, tried to copy the WalletConnectHandler method in the MainMenuScript.cs from the github repo but nothing changes.

here is the full log screenshot :

<img width="1511" alt="Capture d’écran 2022-02-15 à 10 17 24" src="https://user-images.githubusercontent.com/97549458/154031252-9d4d473b-c6a6-4bd6-bd5e-d215855106ba.png">

**Comment by xactant** [comment]
So the error is happening because login is failing.

Let's move this discussion to the forum: https://forum.moralis.io/t/ethereum-unity3d-boilerplate-questions

Please post a copy of your WalletConnectHandler code to the forum.

**Comment by xactant** [comment]
Also, check the error log on the server as soon as you attempt another login. If there are any errors please post them to the forum as well.

**Comment by Oberhaim** [comment]
done !
