### ISSUE TITLE
I got the message "The associated script can not be loaded..." when I clicked MoralisSetup of DemoScene. -> resolved

### ISSUE THREAD

**Issue by hheungsu** [ethereum-boilerplate/ethereum-unity-boilerplate#58]
I imported the package moralisweb3sdk_v1_0_6.unitypackage and followed the tutorial but met the error below when I clicked MoralisSetup of DemoScene :
"The associated script can not be loaded. Please fix any complie errors and open Prefab Mode and assign a valid script to the Prefab Asset."
I use the Unity 2021.2.11f1 and Visual Studio for Mac[8.10.10].
How can I fix this issue?  Please help me!

**Comment by hheungsu** [comment]
When I clicked the play button on VisualStudio and I saw the error message below:

/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.
There was a conflict between "System.Net.Http, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Net.Http, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Net.Http, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [/Applications/Unity/Hub/Editor/2021.2.11f1/Unity.app/Contents/NetStandard/compat/2.1.0/shims/netstandard/System.Net.Http.dll].
        /Applications/Unity/Hub/Editor/2021.2.11f1/Unity.app/Contents/NetStandard/compat/2.1.0/shims/netstandard/System.Net.Http.dll
          Project file item includes which caused reference "/Applications/Unity/Hub/Editor/2021.2.11f1/Unity.app/Contents/NetStandard/compat/2.1.0/shims/netstandard/System.Net.Http.dll".
            System.Net.Http
    References which depend on "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll].
        /Users/heungh/New Unity Project/hhs-choding-fps/My project (4)/Library/PackageCache/com.unity.collab-proxy@1.15.7/Lib/Editor/PlasticSCM/unityplastic.dll
          Project file item includes which caused reference "/Users/heungh/New Unity Project/hhs-choding-fps/My project (4)/Library/PackageCache/com.unity.collab-proxy@1.15.7/Lib/Editor/PlasticSCM/unityplastic.dll".
            unityplastic
        /Users/heungh/New Unity Project/hhs-choding-fps/My project (4)/Library/PackageCache/com.unity.testtools.codecoverage@1.0.1/lib/ReportGenerator/ReportGeneratorMerged.dll
          Project file item includes which caused reference "/Users/heungh/New Unity Project/hhs-choding-fps/My project (4)/Library/PackageCache/com.unity.testtools.codecoverage@1.0.1/lib/ReportGenerator/ReportGeneratorMerged.dll".
            ReportGeneratorMerged (MSB3277) (LeanCommon)

**Comment by hheungsu** [comment]
I fixed the issue by the tutorial (build setting>player>check unsafe code) and build again.

**Comment by xactant** [comment]
Closing as this was solved by the user.

**Comment by lazy1523** [comment]
I'm having the same problem, but it can't be solved by build setting>player>check unsafe code. unity version 2021.2.17f1c1
