### ISSUE TITLE
How to login with just username/email and password?

### ISSUE THREAD

**Issue by vrxgaminginc** [ethereum-boilerplate/ethereum-unity-boilerplate#77]
Is it possible to log in with just username and e-mail?

Is there something equivalent to this JS SDK but in C# SDK?:
const user = await Moralis.User.logIn("myname", "mypass");

**Comment by xactant** [comment]
Yes there is a known issue (Issue #72) with this though.

**Comment by xactant** [comment]
merged

**Comment by ammarvohra** [comment]
I am still unable to login with username and password, here's a simple step what I am doing after initializing the Moralis.
`MoralisUser user = new MoralisUser();
user.username = "email";
user.email = "email";
user.password = "password";
await user.SignUpAsync();`

Let me know if I am missing something.
