### ISSUE TITLE
Signing message has expired

### ISSUE THREAD

**Issue by kuraikage** [ethereum-boilerplate/ethereum-unity-boilerplate#79]
We have encountered this error when we are trying to sign in with certain accounts while everything works perfectly with other accounts that we have. We are not exactly sure what or why this happens
![unknown](https://user-images.githubusercontent.com/13997374/156767901-0cd54e86-86a4-4df7-96f0-9fbfcd635a74.png)
?

**Comment by xactant** [comment]
Make sure you are using a Morailis SDK Package that is 1.0.7 or newer. From your log it looks like the app is not calling the getServerTime Cloud Function and appending this to the Signing Message.

**Comment by kuraikage** [comment]
We are using 1.0.8 now and we still get the below error.

`2022-03-05T08:39:42.917Z - Error: Signing message has expired.
    at /moralis-server/lib/Adapters/Auth/moralisEth.js:48:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)`
    
Please note that it happens with certain accounts but not all.

**Comment by xactant** [comment]
Please confirm that in your WalletConnectHandler (in the demo this is in MainMenuScript) has this block of code at the top of the method:
```
        // Extract wallet address from the Wallet Connect Session data object.
        string address = data.accounts[0].ToLower();
        string appId = MoralisInterface.GetClient().ApplicationId;
        long serverTime = 0;

        // Retrieve server time from Moralis Server for message signature
        Dictionary<string, object> serverTimeResponse = await MoralisInterface.GetClient().Cloud.RunAsync<Dictionary<string, object>>("getServerTime", new Dictionary<string, object>());

        if (serverTimeResponse == null || !serverTimeResponse.ContainsKey("dateTime") ||
            !long.TryParse(serverTimeResponse["dateTime"].ToString(), out serverTime))
        {
            Debug.Log("Failed to retrieve server time from Moralis Server!");
        }

        string signMessage = $"Moralis Authentication\n\nId: {appId}:{serverTime}";

        Debug.Log($"Sending sign request for {address} ...");

        string response = await walletConnect.Session.EthPersonalSign(address, signMessage);
```

If not your code needs to be updated. From what you said though this is not the case.

1. Try re-starting your Moralis server.
2. If you have a test account that is giving the error and one that is not, compare their ACL fields.

I will post this question internally to the server team and see if anyone has other suggestions.

**Comment by kuraikage** [comment]
We looked at our code and found that we were still using the old hardcoded string as the sign message and had not integrated the code you posted above to concatenate the server time to it.

Thanks a lot for your prompt responses. We really appreciate it!
