### ISSUE TITLE
URP Issue

### ISSUE THREAD

**Issue by cbmoosic** [ethereum-boilerplate/ethereum-unity-boilerplate#9]
MainMenuScript not loading in project using URP.

**Comment by xactant** [comment]
I will take a look. 

Something to look at is to click on the UL Panel and look at the MainMenuScript:
1. Is the script there?
2. Is the WalletConnect field populated?

If the answer to either of the above are no, then the UI references have been lost. If this is the case the easiest fix is to delete the MoralisWeb3ApiSdk folder under assets and re-import the package.

If the answer to both is "Yes" please let me know.

I will create a URP project and try it as well.

Regards,

David

**Comment by xactant** [comment]
@cbmoosic,

I have not heard back from you yet. Is this still an issue?

Thank you,

David

**Comment by caiocabralbr** [comment]
Funcionando perfeitamente WebGL e URP aqui!
